name: 🐞 Bug or error report
description: Report an anomaly or unexpected behavior with a sample from this repository.
labels: ['Needs: Triage :mag:', 'type:bug-suspected']

body:
  - type: markdown
    attributes:
      value: |
        ### Bug Report Overview
        Thank you for reporting a bug! Use this template to provide clear and concise information to help resolve the issue.
        
        - Refer to our [How To Create Good Issues](https://github.com/pnp/powerfx-samples/wiki/How-to-Create-Good-Issues).
        - Include all required details; incomplete reports will be flagged and closed.
        - Issues without author mentions may not get addressed.
        - Pull requests are welcome if you have a solution in mind!

  - type: input
    id: sample
    validations:
      required: true
    attributes:
      label: Sample
      description: |
        Which sample are you having troubles with? Provide the sample name or URL.

  - type: input
    id: authors
    validations:
      required: true
    attributes:
      label: Author(s)
      description: |
        Mention the sample's author(s) using their GitHub handle(s). Author details can be found in the sample documentation.

  - type: textarea
    id: describe-bug
    validations:
      required: true
    attributes:
      label: Describe the Bug
      description: Provide a clear and concise description of the bug.
      placeholder: What is the issue?

  - type: textarea
    id: steps
    validations:
      required: true
    attributes:
      label: Steps to Reproduce
      description: Provide detailed steps to reproduce the issue.
      value: |
        1.
        2.
        3.

  - type: textarea
    id: expected
    validations:
      required: true
    attributes:
      label: Expected Behavior
      description: Describe what you expected to happen when the steps are followed.
      placeholder: What did you expect to see?

  - type: textarea
    id: what-happened
    validations:
      required: true
    attributes:
      label: Observed Behavior
      description: Describe what actually happened.
      placeholder: Tell us what you see.

  - type: select
    id: priority
    validations:
      required: true
    attributes:
      label: Priority
      description: |
        Indicate the severity of the issue.
        - P0: Blocks all usage or development.
        - P1: High impact, needs immediate attention.
        - P2: Medium impact, disrupts functionality.
        - P3: Low impact, minor annoyance.
        - P4: No immediate impact, enhancement or low-priority bug.
      options:
        - P0
        - P1
        - P2
        - P3
        - P4

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots/Video
      description: |
        If applicable, add links to screenshots or videos that help explain the problem.
        Annotate impacted areas if possible.
      placeholder: Paste link(s) to screenshots or videos here.

  - type: textarea
    id: desktop-info
    attributes:
      label: Desktop Information
      description: Provide details of your desktop environment.
      value: |
        - OS: [e.g., Windows, macOS, Linux]
        - Browser: [e.g., Chrome, Safari, Firefox]
        - Resolution: [e.g., 1920x1080]
        - Browser Version: [e.g., 95.0]

  - type: textarea
    id: mobile-info
    attributes:
      label: Mobile/Tablet Information
      description: Provide details of your mobile or tablet environment.
      value: |
        - Device: [e.g., iPhone 13, Samsung Galaxy Tab]
        - OS: [e.g., iOS 16, Android 12]
        - Screen Size: [e.g., 6.1", 7"]
        - Browser: [e.g., Safari, Chrome]
        - Browser Version: [e.g., 15.0]

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any additional context or references about the problem.
      placeholder: Include relevant links or explanations.
